project_id = "ehuxmopdfmnbprszkkxr"

[functions.generate-summary]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.personalize-feed]
verify_jwt = false

[functions.fetch-tweets]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false